import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import MegaFooter from "@/components/Footer";
import SiteBanner from "@/components/banner/SiteBanner";

export const metadata: Metadata = {
  title: "Bohemia Health",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SiteBanner />
          <Navbar />
          {children}
          <MegaFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
