import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bohemia Health",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
