import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar/Navbar";
import { ThemeProvider } from "next-themes";
import MegaFooter from "@/components/footer/Footer";
import SiteBanner from "@/components/banner/SiteBanner";
import { BreadcrumbProvider } from "@/components/footer/breadcrumb/context";

export const metadata: Metadata = {
  title: "Bohemia Health",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <BreadcrumbProvider>
            <Navbar />
            <SiteBanner />
            {children}
            <MegaFooter />
          </BreadcrumbProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
